#!/bin/bash
# Create needed user and group
useradd guest
groupadd team

# Create track files
cd /srv
tee -a status.sh << EOF

echo -n "status.sh successfully executed by "
whoami
EOF
chmod 0750 status.sh
tee -a tasks.txt << EOF
1. Finish this Permissions Lab
2. Do the Networking Configuration Basics Lab
3. Listen to the latest episode of RHEL Presents
EOF
chmod 0750 tasks.txt
mkdir proprietary && chmod 0640 proprietary
cd proprietary
echo "You should enjoy the subtle detours." > contract01.txt
echo "to the fullest," > contract02.txt
echo "because that is where you find the things" > contract03.txt
echo "that are more important than what you want." > contract04.txt
chmod 777 *.txt

TMUX='' tmux new-session -d -s 'permissions' > /dev/null 2>&1
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'

cat >> ~/.bashrc <<-EOF

session="permissions"
tmux has-session -t=$session_name 2> /dev/null
if [[ -z "$TMUX" ]]; then
  tmux attach-session -t "$session_name" > /dev/null 2>&1
else
  tmux switch-client -t "$session_name" > /dev/null 2>&1
fi
EOF