#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

yum remove -y google-rhui-client*
yum clean all
yum update -y
yum install -y curl tree bash-completion vim-enhanced

mv /etc/yum.repos.d/google-cloud.repo /etc/yum.repos.d/epel* /root
timedatectl set-timezone America/New_York
