#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

yum install -y dnf curl bash-completion vim-enhanced
dnf remove -y google-rhui-client*
dnf clean all
dnf update -y

mv /etc/yum.repos.d/google-cloud.repo /root