#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

virsh start centos

echo "${SSHKEY}" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh-keygen -f /root/.ssh/id_rsa -y > /root/.ssh/id_rsa.pub

usermod -aG wheel rhel

# MAC Addresses
# vm1:          52:54:00:d6:0c:72
# centos:       52:54:00:68:79:84
# rhel07:       52:54:00:02:ce:bb
# rhel08:       52:54:00:43:26:d3
# rhel09:       52:54:00:7f:e1:4e


# Get the IP of the VM belonging to vm1 based on arp.
while ! [ $( arp -an | grep 52:54:00:68:79:84 | awk '{print $2}' | tr -d '()' )  ]; do echo "Waiting for arp to return centos MAC address."; sleep 10; done;
echo "$( arp -an | grep 52:54:00:68:79:84 | awk '{print $2}' | tr -d '()' ) centos" >> /etc/hosts

usermod -aG wheel rhel
echo redhat | passwd --stdin rhel

while ! ping -c 1 -W 1 centos; do echo "Waiting for centos - network interface might be down."; sleep 10; done;

ssh -i /root/.ssh/id_rsa -o "StrictHostKeyChecking no" root@centos "subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force"

# set up SSL for certificate signing
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

#check web console url for certificate
echo https://${HOSTNAME}.${_SANDBOX_ID}.instruqt.io:9090

#also go ahead and echo it to a text file as well just for good measure
echo https://${HOSTNAME}.${_SANDBOX_ID}.instruqt.io:9090 >> ~/webconsoleurl.txt

ssh -o "StrictHostKeyChecking no" root@centos -t 'yum clean all && yum update --exclude=kernel -y && yum autoremove -y'
ssh -o "StrictHostKeyChecking no" root@centos -t 'nmcli dev con enp1s0'
