#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

virsh start centos

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

usermod -aG wheel rhel
echo redhat | passwd --stdin rhel

echo "${SSHKEY}" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh-keygen -f /root/.ssh/id_rsa -y > /root/.ssh/id_rsa.pub

# MAC Addresses
# vm1:      52:54:00:d6:0c:72
# centos:   52:54:00:68:79:84

# Get the IP of the VM belonging to vm1 based on arp.
while ! [ $( arp -an | grep 52:54:00:68:79:84 | awk '{print $2}' | tr -d '()')  ]; do echo "Waiting for arp to return centos MAC address."; sleep 1; done;
echo "$( arp -an | grep 52:54:00:68:79:84 | awk '{print $2}' | tr -d '()' ) centos" >> /etc/hosts

while ! ping -c 1 -W 1 centos; do echo "\nWaiting for centos - network interface might be down."; sleep 1; done;
sleep 15
TMUX='' tmux new-session -d -s 'centos' 'ssh -o "StrictHostKeyChecking no" root@centos; clear'

tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'