#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=image_builder --org=12451665 --force

yum install -y curl bash-completion vim-enhanced
yum remove -y google-rhui-client*
mv /etc/yum.repos.d/google-cloud.repo /root
yum clean all
yum update -y