#!/bin/bash
#creates a directory for code
mkdir /home/C_source

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "trashing GCP repos" >> /root/post-run.log
mv /etc/yum.repos.d/google-cloud.repo /root

#set up tmux
TMUX='' tmux new-session -d -s 'rhel-session' > /dev/null 2>&1
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'


#install a program that will manage tmux mouse input much more smoothly - i.e., it will enable easy mouse scrolling
git clone https://github.com/nhdaly/tmux-better-mouse-mode
./scroll_copy_mode.tmux
tmux source-file tmux.conf

echo "DONE" >> /root/post-run.log
