#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
   echo "Waiting for Instruqt to finish booting the VM"
   sleep 1
done

subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force
dnf install -y stress-ng
echo "rhel:redhat" | chpasswd
echo "rhel     ALL=(ALL)     NOPASSWD: ALL" > /etc/sudoers.d/rhel
