#!/bin/bash

dnf group install -y "Development Tools"
dnf copr enable -y @rhel-lightspeed/command-line-assistant

# echo `agent variable get cla_version` > /root/ver.txt
dnf install -y `agent variable get cla_version`
