#!/bin/bash
LOG=/root/setup-log
#LOG=/dev/null




subscription-manager config --rhsm.manage_repos=1 >> $LOG
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force >> $LOG

dnf install -y rhc >> $LOG

subscription-manager unregister >> $LOG
subscription-manager clean >> $LOG

echo "export KEY='rhc-lab'" >> /root/.bashrc



#set up tmux so it has to restart itself whenever the system reboots

#step 1: make a script
tee ~/startup-tmux.sh << EOF
TMUX='' tmux new-session -d -s 'rhel-session' > /dev/null 2>&1
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'
tmux set -g mouse on
tmux set mouse on
EOF

#step 2: make it executable
chmod +x ~/startup-tmux.sh
#step 3: use cron to execute 
echo "@reboot ~/startup-tmux.sh" | crontab -

#step 4: start tmux for the lab
~/startup-tmux.sh

hostnamectl set-hostname rhel-$(uuidgen | cut -c 32-)
exec $SHELL