#!/bin/bash
# while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
# do
#     echo "Waiting for Instruqt to finish booting the VM"
#     sleep 1
# done

# while ! ping -c 1 -W 1 upgraded08; do echo "Waiting for VM - network interface might be down..."; sleep 10; done

# TMUX='' tmux new-session -d -s 'upgraded08' 'ssh -o "StrictHostKeyChecking no" rhel@upgraded08; sudo -i; clear' > /dev/null 2>&1
# tmux set -g pane-border-status top
# tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'
# while ! [ $( arp -an | grep 52:54:00:22:37:93 | awk '{print $2}' | tr -d '()' )  ]; do echo "Waiting for arp to return upgraded08 MAC address."; sleep 10; done;
# echo "$( arp -an | grep 52:54:00:22:37:93 | awk '{print $2}' | tr -d '()' ) upgraded08" >> /etc/hosts
