#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

mv /etc/yum.repos.d/google-cloud.repo /root

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

timedatectl set-timezone America/New_York
usermod -aG wheel rhel
echo redhat | passwd --stdin rhel
