#!/bin/bash

echo "This is the cleanup script"

podman container rm --all --force #get trid of the containers made in step 1
podman image rm --all --force #get rid of the container images used in step 1

dnf remove container-tools # get rid of the tools the user installed earlier so they have a fresh start in step 2

exit 0