version: "3"
virtualmachines:
- name: rhel
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-10-0-09-09-25
  shell: /bin/bash
  environment:
    cla_version: command-line-assistant*.main*.el9.noarch
  machine_type: n2-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: ACTIVATION_KEY
