#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
   echo "Waiting for Instruqt to finish booting the VM"
   sleep 1
done

yum remove -y google-rhui-client-rhel8.noarch
yum clean all
subscription-manager config --rhsm.manage_repos=1
# subscription-manager register --activationkey=Instruqt_system_registration --org=12451665 --force
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force
dnf install -y tree tmux

# November 16th - libbpf got updated and broke the lab. bcc tools won't work unless libbpf is updated.
dnf update -y libbpf
