#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

if ! [[ $(chronyc sources | cat | grep "Number of sources = 2" ) = *"Number of sources = 2"* ]]; then 
  fail-message "The time servers were not configured properly."
  exit 1
fi