#!/bin/bash
set -euxo pipefail

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

sed -ie 's/enable_partial_images = "true"/enable_partial_images = "false"/' /etc/containers/storage.conf

# install the good image
podman run --rm --privileged -v /dev:/dev -v /var/lib/containers:/var/lib/containers -v /:/target \
--pid=host --security-opt label=type:unconfined_t \
builder.${INSTRUQT_PARTICIPANT_ID}.instruqt.io:5000/ecommsite:latest \
bootc install to-existing-root --root-ssh-authorized-keys /target/root/.ssh/authorized_keys \
--acknowledge-destructive

 systemd-run --on-active=10 reboot