#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the setup script"
podman container rm --all --force #get trid of the containers made in step 1
podman image rm --all --force #get rid of the container images used in step 1
exit 0
