#!/bin/bash
set -euxo pipefail

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

echo "Adding wheel" > /root/post-run.log
useradd rhel
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "DONE" >> /root/post-run.log

timedatectl set-timezone America/New_York

dnf remove -y tmux

# Edit the wireguard if wg0 to point at satellite. Then create the interface with nmcli.
sed -i "/^Endpoint /s/=.*$/= satellite.${_SANDBOX_ID}.svc.cluster.local:51820/" /etc/wireguard/wg0.conf
sed -i "s/Address =/#Address =/" /etc/wireguard/wg0.conf
#nmcli connection import type wireguard file /etc/wireguard/wg0.conf
wg setconf wg0 /etc/wireguard/wg0.conf