#!/bin/bash
set -euxo pipefail

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

echo "Setup script for satellite"

echo "Adding wheel" > /root/post-run.log
useradd rhel
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "DONE" >> /root/post-run.log

echo "export LANG=en_US.UTF-8" >> /root/.bashrc

rm -rf /home/myee/manifest_satellite-*

# Add satellite.lab to hosts entry.
sed -ie 's/svc.cluster.local/& satellite.lab/g' /etc/hosts