#!/bin/bash
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

dnf install -y man-db

# creating sample data
/usr/bin/touch {anaconda-ks.cfg,original-ks.cfg}
/usr/bin/mkdir /root/openscap_data
/usr/bin/touch /root/openscap_data/{eval_remediate_report.html,eval_remediate_results.xml}

# add rhel user to wheel
/usr/sbin/usermod -a -G wheel rhel
# allow passwordless sudo for wheel group
/usr/bin/sed -i '
    /%wheel\s\+ALL=(ALL)\s*NOPASSWD:\s*LOG_INPUT:\s*LOG_OUTPUT:\s*ALL/{
        s/^#\+\s*//
        b
    }
    /^[^#].*wheel/s/^/#/
    ' /etc/sudoers
/usr/bin/sed -i 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+NOPASSWD:\s\+ALL\)/\1/' /etc/sudoers

mv /etc/yum.repos.d/google-cloud.repo /root
timedatectl set-timezone America/New_York

#set up tmux so it has to restart itself whenever the system reboots

#step 1: make a script
tee ~/startup-tmux.sh << EOF
TMUX='' tmux new-session -d -s 'rhel-session' > /dev/null 2>&1
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'
tmux set -g mouse on
tmux set mouse on
EOF

#step 2: make it executable
chmod +x ~/startup-tmux.sh
#step 3: use cron to execute 
echo "@reboot ~/startup-tmux.sh" | crontab -

#step 4: start tmux for the lab
~/startup-tmux.sh