#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
   echo "Waiting for Instruqt to finish booting the VM"
   sleep 1
done

yum remove -y google-rhui-client-rhel8.noarch
yum clean all
subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

#Create an output file
touch /root/post-run.log

export HOSTNAME=`hostname --all-fqdns`

systemctl restart firewalld

firewall-cmd --zone=public --add-service=http 
firewall-cmd --reload

dnf install -y httpd wget
systemctl restart httpd
systemctl --now enable httpd

#Get the sample database file
wget https://raw.githubusercontent.com/rhel-labs/learn-katacoda/master/pcp-flamegraphs/sample-testdata.sql

#Create a done file to signal we have finished
touch /root/post-run.log.done

n=1
GREEN='\033[0;32m' 
NC='\033[0m' # No Color

while [ ! -f /root/post-run.log.done ] ;
do
      if test "$n" = "1"
      then
	    clear
            n=$(( n+1 ))	 # increments $n
      else
	    printf "."
      fi
      sleep 2
done
clear
echo -e "${GREEN}Ready to start your scenario${NC}"
