#!/bin/bash

set -euxo pipefail

echo "downloading pello tarball"
wget -P /home/rhel/downloads \
    https://files.pythonhosted.org/packages/source/P/Pello/Pello-1.0.4.tar.gz
chown rhel: /home/rhel/downloads/Pello-1.0.4.tar.gz