#!/bin/bash

# start the jupyter notebook and allow it to run in the background (note that this exists because the one that the user created won't persist between steps in instruqt) (also, make sure the user installed everything)
conda run -n tf pip install notebook matplotlib tensorflow-cpu
nohup conda run -n tf jupyter notebook --ip=* --no-browser --allow-root -NotebookApp.password='redhat' -NotebookApp.token='redhat' --notebook-dir="/root/tensorflow" </dev/null >/dev/null 2>&1 &

