#!/bin/sh
TMUX='' tmux new-session -d -s 'networking-setup' 'ssh -o "StrictHostKeyChecking no" rhelvm; clear' > /dev/null 2>&1
# tmux split-window -v 'ssh -o "StrictHostKeyChecking no" rhelvm; clear'
# tmux select-layout even-vertical
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'

cat >> ~/.bashrc <<-EOF

session="networking-setup"
tmux has-session -t=$session_name 2> /dev/null
if [[ -z "$TMUX" ]]; then
  tmux attach-session -t "$session_name" > /dev/null 2>&1
else
  tmux switch-client -t "$session_name" > /dev/null 2>&1
fi
EOF

ssh root@rhelvm 'nmcli connection delete Wired\ connection\ 1'
ssh root@rhelvm 'subscription-manager register --activationkey=Instruqt_system_registration --org=12451665 --force'