#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

while ! ping -c 1 -W 1 centos; do echo "Waiting for centos - network interface might be down."; sleep 10; done;

# Change the hostname of the centos to something unique.

centosid="centos-conversion-$(uuidgen | cut -c 32-)"
agent variable set vmid "$centosid"
#ssh -o "StrictHostKeyChecking no" root@centos hostnamectl set-hostname centos-conversion-$(uuidgen | cut -c 32-)
#ssh -o "StrictHostKeyChecking no" root@centos hostnamectl set-hostname centos-conversion-"$centosid"
ssh -o "StrictHostKeyChecking no" root@centos hostnamectl set-hostname "$centosid"
