#!/bin/bash
virsh start rhel10beta

echo "${SSHKEY}" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh-keygen -f /root/.ssh/id_rsa -y > /root/.ssh/id_rsa.pub

subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "trashing GCP repos" >> /root/post-run.log
mv /etc/yum.repos.d/google-cloud.repo /root

# MAC Addresses
# vm1:          52:54:00:d6:0c:72
# centos:       52:54:00:68:79:84
# rhel07:       52:54:00:02:ce:bb
# rhel08:       52:54:00:43:26:d3
# rhel09:       52:54:00:7f:e1:4e
# rhel10beta:   52:54:00:5b:ec:6f


# Get the IP of the VM belonging to vm1 based on arp.
while ! [ $( arp -an | grep 52:54:00:5b:ec:6f | awk '{print $2}' | tr -d '()' )  ]; do echo "Waiting for arp to return rhel10beta MAC address."; sleep 10; done;
echo "$( arp -an | grep 52:54:00:5b:ec:6f | awk '{print $2}' | tr -d '()' ) rhel10beta" >> /etc/hosts

while ! ping -c 1 -W 1 rhel10beta; do echo "Waiting for rhel10beta - network interface might be down."; sleep 10; done;

ssh -i /root/.ssh/id_rsa -o "StrictHostKeyChecking no" root@rhel10beta "subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force"
