#!/bin/bash
# until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
# do
#     echo "Waiting for Instruqt to finish booting the VM"
#     sleep 1
# done

#dnf -y install subscription-manager
subscription-manager register --org=12451665 --activationkey=Instruqt_system_registration --force

tee -a soe.yml << EOF
---
- hosts: localhost
  vars:
    kernel_settings_sysctl:
      - name: vm.swappiness
        value: 20
      - name: vm.dirty_ratio
        value: 40
      - name: vm.dirty_expire_centisecs
        value: 500
      - name: vm.dirty_writeback_centisecs
        value: 100
      - name: kernel.sem
        value: "250 32000 100 128"
    tlog_scope_sssd: all
  roles:
    - role: rhel-system-roles.kernel_settings
    - role: rhel-system-roles.tlog
EOF

mkdir -p /root/.cloudrepos
mv /etc/yum.repos.d/google-cloud.repo /root/.cloudrepos/
mv /etc/yum.repos.d/rh-cloud.repo /root/.cloudrepos/

#useradd rhel
echo -e "test\ntest" | passwd rhel
mkdir -p /home/rhel/.ssh
cp .ssh/id_rsa.pub /home/rhel/.ssh/
cp .ssh/authorized_keys /home/rhel/.ssh/
chown rhel:rhel -R /home/rhel/.ssh/

ssh-keyscan -H client2 >> ~/.ssh/known_hosts
ssh-keyscan -H client1 >> ~/.ssh/known_hosts