#!/bin/bash
podman pod stop --all && podman pod rm --all
cat << EOF >> /root/my-networked-pod.kube
[Install]
WantedBy=default.target

[Unit]
# You can use standard unit options to control the start-up order of your pod. 
# Such as:
#After=
#Requires=

[Kube]
# In this section you can define several things
# here we are simply calling the kube yaml we generated with podman
Yaml=/etc/containers/systemd/my-networked-pod.yaml

#We also need to define the ports that our pod maps int, just as we do a the pod level
PublishPort=8080:80
EOF
