#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the setup script"
mkdir /root/quantum
#download a demo for the user to try
wget --directory-prefix=/root/quantum/ https://raw.githubusercontent.com/Qiskit/qiskit-tutorials/master/tutorials/circuits/1_getting_started_with_qiskit.ipynb

#get rid of the existing samples in there. I want the user to only see their work, so we can clear the original output with a python program that will be made and run here
# note: this program is not essential and can totally be removed if there are issues. It was only added because I (Will) thought it would improve the user experience.
tee /root/quantum/notebooksetup.py << EOF
import nbformat

#load the notbook
with open('/root/quantum/1_getting_started_with_qiskit.ipynb','r', encoding='utf-8') as f:
    notebook = nbformat.read(f, as_version=4)

#clear the existing outputs
for cell in notebook.cells:
    if cell.cell_type == 'code':
        cell.outputs= []

#save the revised notebook
with open('/root/quantum/1_getting_started_with_qiskit.ipynb','w', encoding='utf-8') as f:
    nbformat.write(notebook, f)
EOF
conda run -n qis python /root/quantum/notebooksetup.py
rm /root/quantum/notebooksetup.py
exit 0
