version: "3"
virtualmachines:
- name: rhel
  image: projects/tmm-instruqt-11-26-2021/global/images/image-mode-3-virt-rhel-9-4-10-11-24
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n2-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  nested_virtualization: true
secrets:
- name: REG_SVC_ACCT
- name: ACTIVATION_KEY
