name: satellite
slug: satellite
description: A long description of the track.
virtualmachines:
- name: rhel1
  image: projects/tmm-instruqt-11-26-2021/global/images/satellite-lab-client1-05-27-24
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  memory: 4096
  cpus: 1
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: rhel2
  image: projects/tmm-instruqt-11-26-2021/global/images/satellite-lab-client2-05-27-24
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  memory: 4096
  cpus: 1
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: satellite
  image: projects/tmm-instruqt-11-26-2021/global/images/satellite-advanced-server-05-27-24-2
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-4
  memory: 16384
  cpus: 4
  allow_external_ingress:
  - http
  - https
  - high-ports
secrets:
- name: ACTIVATION_KEY
