version: "3"
virtualmachines:
- name: rhel
  image: projects/tmm-instruqt-11-26-2021/global/images/virt-rhel-9-5-01-27-25-rhel10isos
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  nested_virtualization: true
