#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
   echo "Waiting for Instruqt to finish booting the VM"
   sleep 1
done

yum remove -y google-rhui-client-rhel8.noarch
yum clean all
subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

firewall-cmd --zone=public --add-service=https --permanent
firewall-cmd --reload

dnf install -y httpd
systemctl --now enable httpd
update-crypto-policies --set FUTURE
#systemctl restart httpd.service > /dev/null 2>&1
