#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails.
#

tee -a /root/reset << EOF
all:
  hosts:
    vm1:
  vars:
    firewall:
      - previous: replaced
EOF

ansible-playbook -i reset -b firewall.yml
