#!/bin/sh
while ! ping -c 1 -W 1 192.168.122.2; do echo "Waiting for rhelvm - network interface might be down..."; sleep 1; done

echo "192.168.122.2 rhelvm" >> /etc/hosts
ssh -o "StrictHostKeyChecking no" -i r4ekey root@rhelvm subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

TMUX='' tmux new-session -d -s 'firewall-testing' > /dev/null 2>&1
TMUX='' tmux new-session -d -s 'firewall-testing-rhelvm' 'ssh -o "StrictHostKeyChecking no" root@rhelvm; clear' > /dev/null 2>&1

tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'
