#!/bin/sh
while ! ping -c 1 -W 1 192.168.122.2; do echo "Waiting for rhelvm - network interface might be down..."; sleep 1; done

echo "192.168.122.2 rhelvm" >> /etc/hosts
ssh -o "StrictHostKeyChecking no" -i r4ekey root@rhelvm subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

TMUX='' tmux new-session -d -s 'firewall-testing' > /dev/null 2>&1
TMUX='' tmux new-session -d -s 'firewall-testing-rhelvm' 'ssh -o "StrictHostKeyChecking no" root@rhelvm; clear' > /dev/null 2>&1
# tmux split-window -v 'ssh -o "StrictHostKeyChecking no" -i r4ekey root@rhelvm; clear'
# tmux select-layout even-vertical
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'

# cat >> ~/.bashrc <<-EOF

# session_name="firewall-testing"
# tmux has-session -t=$session_name 2> /dev/null
# if [[ -z "$TMUX" ]]; then
#   tmux attach-session -t "$session_name" > /dev/null 2>&1
# else
#   tmux switch-client -t "$session_name" > /dev/null 2>&1
# fi
# EOF
