#!/bin/sh
ssh rhelvm subscription-manager register --activationkey=Instruqt_system_registration --org=12451665 --force

TMUX='' tmux new-session -d -s 'firewall-testing' > /dev/null 2>&1
tmux split-window -v 'ssh -o "StrictHostKeyChecking no" rhelvm; clear'
tmux select-layout even-vertical
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'

cat >> ~/.bashrc <<-EOF

session="firewall-testing"
tmux has-session -t=$session_name 2> /dev/null
if [[ -z "$TMUX" ]]; then
  tmux attach-session -t "$session_name" > /dev/null 2>&1
else
  tmux switch-client -t "$session_name" > /dev/null 2>&1
fi
EOF
