#!/bin/bash
set -euxo pipefail

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

# Log into terms based registry and stage bootc and bib images
podman login -u='1979710|rhel-tmm' -p=${REG_SVC_ACCT} registry.redhat.io
podman pull registry.redhat.io/rhel9/rhel-bootc:9.4 registry.redhat.io/rhel9/bootc-image-builder:latest

# Some shortcuts for users
# reglogin - uses podman secret to log into the terms based registry in case creds time out or initial pull fails
# registry ENV variable -  the registry target created for the lab
printf ${REG_SVC_ACCT} | podman secret create regpass -
cat <<EOF >> /root/.bashrc
export REGISTRY="${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io:5000"
alias reglogin="podman login -u='1979710|rhel-tmm' --secret regpass registry.redhat.io"
alias bc-build="podman build -t ${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io:5000/test-bootc ."
alias bc-push="podman push ${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io:5000/test-bootc"
EOF

echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

# set up SSL for fully functioning registry
# Enable EPEL for RHEL 9
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
dnf install -y certbot

# stop the process that is using TCP port 80; we need that port open for certbot
# fuser -k 80/tcp

# request certificates
certbot certonly --standalone --preferred-challenges http -d ${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io --non-interactive --agree-tos -m trackbot@instruqt.com -v

# run a local registry with the provided certs
podman run --privileged -d \
  --name registry \
  -p 5000:5000 \
  -v /etc/letsencrypt/live/${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io/fullchain.pem:/certs/fullchain.pem \
  -v /etc/letsencrypt/live/${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io/privkey.pem:/certs/privkey.pem \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/fullchain.pem \
  -e REGISTRY_HTTP_TLS_KEY=/certs/privkey.pem \
  registry:2


# add hostname to runtime variable

agent variable set CONTAINER_REGISTRY_ENDPOINT ${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io:5000

# set up the environmen to run the RHDP makefile and showroom

dnf -y install git libvirt-nss make lorax
git clone -b rh1-lab --single-branch https://github.com/nzwulfin/rh-summit-2024-lb1506.git
git clone -b rh1-lab --single-branch https://github.com/nzwulfin/rh-summit-2024-lb1506-showroom.git
sed -i 's/hosts:      files dns myhostname/hosts:      files libvirt libvirt_guest dns myhostname/' /etc/nsswitch.conf

cd /root/rh-summit-2024-lb1506-showroom
podman run -d --rm --name antora -v $PWD:/antora:Z -p 8500:8080 -i -t ghcr.io/juliaaano/antora-viewer

cd /root/rh-summit-2024-lb1506
cp examples/01.Containerfile Containerfile
make setup

