#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

while ! ping -c 1 -W 1 centos; do echo "Waiting for centos - network interface might be down."; sleep 10; done;
