#!/bin/bash
set -euxo pipefail

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

echo "Setup script for satellite"

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

echo "Adding wheel" > /root/post-run.log
useradd rhel
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "DONE" >> /root/post-run.log

echo "export LANG=en_US.UTF-8" >> /root/.bashrc

hammer -u admin -p bc31c9a6-9ff0-11ec-9587-00155d1b0702 subscription upload --file /home/myee/manifest_satellite-6.10-instruqt_20230425T175412Z.zip --organization "Acme Org"
rm -rf /home/myee/manifest_satellite-6.10-instruqt_*

hammer subscription refresh-manifest --organization "Acme Org"
