#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# Standard Track configuration for subscription manager and user
subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

echo "Adding rhel to wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "enable bash completion in the root's instruqt shell" >> /root/post-run.log
echo "source /etc/profile.d/bash_completion.sh" >> /root/.bashrc

# Enable cockpit
systemctl enable --now cockpit.socket

# Enable the firewall for cockpit and httpd
firewall-cmd --permanent --add-service cockpit 
firewall-cmd --permanent --add-service http
firewall-cmd --reload

# Install the ipa-client packages
dnf -y install bind-utils
dnf -y install ipa-client

# Configure the script variables
export IDM_SERVER_NAME=idmserver.${_SANDBOX_ID}.instruqt.io
export IDM_REPLICA_NAME=idmreplica.${_SANDBOX_ID}.instruqt.io
export IDM_CLIENT_NAME=idmclient.${_SANDBOX_ID}.instruqt.io

echo "setup the simple http app" >> /root/post-run.log

# install httpd components
dnf -y install httpd mod_wsgi

# ditch the default conf file
rm -f /etc/httpd/conf.d/welcome.conf

mv /etc/yum.repos.d/google-cloud.repo /root

timedatectl set-timezone America/New_York

