#!/bin/sh
TMUX='' tmux new-session -d -s 'containers-podman-deploy' > /dev/null 2>&1
tmux split-window -v
tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'

cat >> ~/.bashrc <<-EOF

session="containers-podman-deploy"
tmux has-session -t=$session_name 2> /dev/null
if [[ -z "$TMUX" ]]; then
  tmux attach-session -t "$session_name" > /dev/null 2>&1
else
  tmux switch-client -t "$session_name" > /dev/null 2>&1
fi
EOF
