#!/bin/bash

set -euxo pipefail

echo "downloading bello tarball"
wget -P /home/centos/downloads \
    https://github.com/redhat-developer/rpm-packaging-guide/raw/master/example-code/bello-0.1.tar.gz
chown centos: /home/centos/downloads/bello-0.1.tar.gz