#!/bin/bash
set -euxo pipefail

# Getting a consistent exit code terraform recognizes from a reboot is hard...
# ssh -o StrictHostKeyChecking=no webserver shutdown -r now "Testing oldskool"
# rm /root/.ssh/known_hosts