#!/bin/bash
skopeo inspect docker://${HOSTNAME}.${INSTRUQT_PARTICIPANT_ID}.instruqt.io:5000/test-bootc |  jq ".Digest" > ~/image2.sha

if diff ~/image1.sha ~/image2.sha
then
    fail-message "The update needs to be available in the registry before moving to the next step. Did you push the image to the registry?"
    exit 1
fi

