#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the setup script"
#install MySQL for our test database
dnf install -y mysql-server
#use systemctl to start and enable mysql
systemctl start mysqld.service
systemctl enable mysqld.service
#check the status for debugging purposes
systemctl status mysqld
#set up a database (there is no password for the root user)
mysql -u root --skip-password --execute="CREATE DATABASE Population;"
mysql -u root --skip-password --execute="USE Population;"
mysql -u root --skip-password -D Population --execute="CREATE TABLE Singapore_Population (Year DATE NOT NULL, Population int);"
# put some data into our database
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2022-01-01',5637022);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2021-01-01',5453566);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2020-01-01',5685807);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2019-01-01',5703569);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2018-01-01',5638676);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2017-01-01',5612253);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2016-01-01',5607283);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2015-01-01',5535002);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2014-01-01',5469724);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2013-01-01',5399162);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2012-01-01',5312437);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2011-01-01',5183688);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2010-01-01',5076732);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2009-01-01',4987573);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2008-01-01',4839396);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2007-01-01',4588599);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2006-01-01',4401365);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2005-01-01',4265762);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2004-01-01',4166664);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2003-01-01',4114826);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2002-01-01',4175950);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2001-01-01',4138012);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('2000-01-01',4027887);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1999-01-01',3958723);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1998-01-01',3927213);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1997-01-01',3796038);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1996-01-01',3670704);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1995-01-01',3524506);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1994-01-01',3419048);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1993-01-01',3313471);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1992-01-01',3230698);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1991-01-01',3135083);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1990-01-01',3047132);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1989-01-01',2930901);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1988-01-01',2846108);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1987-01-01',2774789);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1986-01-01',2733373);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1985-01-01',2735957);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1984-01-01',2732221);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1983-01-01',2681061);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1982-01-01',2646466);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1981-01-01',2532835);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1980-01-01',2413945);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1979-01-01',2383500);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1978-01-01',2353600);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1977-01-01',2325300);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1976-01-01',2293300);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1975-01-01',2262600);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1974-01-01',2229800);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1973-01-01',2193000);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1972-01-01',2152400);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1971-01-01',2112900);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1970-01-01',2074507);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1969-01-01',2042500);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1968-01-01',2012000);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1967-01-01',1977600);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1966-01-01',1934400);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1965-01-01',1886900);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1964-01-01',1841600);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1963-01-01',1795000);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1962-01-01',1750200);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1961-01-01',1702400);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1960-01-01',1646400);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1959-01-01',1587200);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1958-01-01',1518800);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1957-01-01',1445929);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1956-01-01',1371600);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1955-01-01',1305500);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1954-01-01',1248200);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1953-01-01',1191800);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1952-01-01',1127000);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1951-01-01',1068100);"
mysql -u root --skip-password -D Population --execute="INSERT INTO Singapore_Population (Year, Population) VALUES ('1950-01-01',1022100);"

#add a consistent ip address for eth0 so we can set up container networking
ip addr add 10.5.0.1 dev eth0
#configure mysql to work with networking
/usr/bin/mysqladmin --bind-address=0.0.0.0
mysql -u root --skip-password -D Population --execute="UPDATE mysql.user SET host='%' WHERE user='root';"
systemctl restart mysqld
exit 0