version: "3"
virtualmachines:
- name: rhel1
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-9-2-6-20-23
  environment:
    "": ""
  machine_type: n1-standard-1
  allow_external_ingress:
  - http
  - https
  - high-ports
  nested_virtualization: true
aws_accounts:
- name: myee
  iam_policy: |-
    {
      "Version": "2012-10-17",
      "Statement": [
        {
            "Sid":"EC2DefaultAllow",
            "Effect": "Allow",
            "Action": "ec2:*",
            "Resource": "*"
        }
      ]
    }
  scp_policy: |-
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "RequireLessThanXLInstanceType",
          "Effect": "Deny",
          "Action": "ec2:RunInstances",
          "Resource": "arn:aws:ec2:::instance/*",
          "Condition": {
            "StringNotEquals": {
              "ec2:InstanceType": [
                "t2.nano"
              ]
            }
          }
        }
      ]
    }
secrets:
- name: ACTIVATION_KEY
- name: SSHKEY
