version: "3"
virtualmachines:
- name: rhel
  image: 'image: projects/tmm-instruqt-11-26-2021/global/images/rhel-9-5-11-27-24'
  machine_type: n1-standard-2
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
secrets:
- name: ACTIVATION_KEY
