#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

stratis filesystem create my_pool my_fs
mkdir /mnt/test_mnt
mount /dev/stratis/my_pool/my_fs /mnt/test_mnt
touch /mnt/test_mnt/my_first_file
touch /mnt/test_mnt/my_second_file