#!/bin/sh
while ! ping -c 1 -W 1 rhel08; do echo "Waiting for VM - network interface might be down..."; sleep 10; done

TMUX='' tmux new-session -d -s 'rhel08' 'ssh -o "StrictHostKeyChecking no" -i ~/.ssh/id_rsa root@rhel08; clear' > /dev/null 2>&1

tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'
