#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

ssh -i ~/.ssh/id_rsa rhel@rhel07 "sudo subscription-manager unregister"

subscription-manager unregister
