#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=Instruqt_system_registration --org=12451665 --force

timedatectl set-timezone America/New_York

# setup webui
firewall-cmd --add-service=cockpit --permanent
firewall-cmd --reload
systemctl enable --now cockpit.socket

# configure vm terminal
tmux new-session -d -s 'rhelvm' ssh -i .ssh/id_rsa root@rhelvm > /dev/null 2>&1

cat >> ~/.bashrc <<-EOF

# tmux session config
session="rhelvm"

tmux has-session -t $session_name 2> /dev/null
if [[ -z "$TMUX" ]]; then
  tmux attach-session -t "$session_name" > /dev/null 2>&1
else
  tmux switch-client -t "$session_name" > /dev/null 2>&1
fi

EOF