#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

yum install -y dnf curl bash-completion vim-enhanced
dnf remove -y google-rhui-client*

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

mv /etc/yum.repos.d/google-cloud.repo /etc/yum.repos.d/epel.repo /etc/yum.repos.d/epel-testing.repo /tmp/
dnf clean all
dnf update -y