#!/bin/sh
while ! ping -c 1 -W 1 192.168.122.112; do echo "Waiting for centos - network interface might be down..."; sleep 10; done

echo "192.168.122.112 centos" >> /etc/hosts

TMUX='' tmux new-session -d -s 'centos' 'ssh -o "StrictHostKeyChecking no" root@centos; clear' > /dev/null 2>&1

tmux set -g pane-border-status top
tmux setw -g pane-border-format ' #{pane_index} #{pane_current_command}'
