#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

tee -a /root/hosts << EOF
      - port: ['9999/tcp']
        state: enabled
EOF

ansible-playbook -i hosts -b firewall.yml
