#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

#if [[ $(subscription-manager repos --list-enabled | grep ansible-2.9-for-rhel-8-x86_64-rpms) = *ansible-2.9-for-rhel-8-x86_64-rpms* ]] && [[ $(rpm -q ansible | grep ansible) = *ansible* ]] && [[ $(rpm -q rhel-system-roles | grep rhel-system-roles) = *rhel-system-roles* ]]; then
#  echo "ansible repo exists"
#fi

#if ! [[ $(subscription-manager repos --list-enabled | grep ansible-2.9-for-rhel-8-x86_64-rpms) = *ansible-2.9-for-rhel-8-x86_64-rpms* ]]; then
  #echo "FAIL: ansible-2.9-for-rhel-8-x86_64-rpms not enabled."
#  fail-message "Your challenge failed because ansible-2.9-for-rhel-8-x86_64-rpms repo is not enabled."
#  exit 1
#fi

if ! [[ $(rpm -q rhel-system-roles | grep rhel-system-roles) = *rhel-system-roles* ]]; then
  #echo "FAIL: The rhel-system-roles package is not installed."
  fail-message "The rhel-system-roles package is not installed."
  exit 1
fi