#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

# This is only required for labs with nested virtualization like networking-basics, rhel for edge, firewall-system-role.
echo "${SSHKEY}" > /root/sshkey
chmod 600 /root/sshkey

mv /etc/yum.repos.d/google-cloud.repo /root
timedatectl set-timezone America/New_York