#!/bin/bash

subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

# Create a new hostname.
rhelid="rhel-$(uuidgen | cut -c 32-)"
hostnamectl set-hostname "$rhelid"

# Register the hostname as an instruqt runtime variable.
agent variable set newhostname "$rhelid"

# The following will trigger insights advisor rule matches.
sed -i 's/ClientAliveInterval.*900//g' /etc/ssh/sshd_config
sed -i '/\[rhel-9-for-x86_64-baseos-rpms\]/,/^ *\[/ s/gpgcheck = 1/gpgcheck = 0/' /etc/yum.repos.d/redhat.repo
sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config

# I think we need this to force insights-client to use the new hostname.
sed -i 's/rhel-9.*/'"$rhelid"'/g' /etc/hosts