#!/bin/bash

subscription-manager repos --disable codeready-builder-for-rhel-9-$(arch)-rpms #make sure that EPEL is not enabled. We want the user to do it themselves
dnf remove -y epel #see the comment above^
