#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# systemctl enable --now cockpit.socket

virsh start vm1

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

dnf install -y nc

systemctl enable --now libvirtd


echo "${SSHKEY}" > r4ekey
chmod 600 r4ekey

# MAC Addresses
# vm1:          52:54:00:d6:0c:72
# centos:       52:54:00:68:79:84
# converted:    52:54:00:87:d3:fc
# rhel07:       52:54:00:02:ce:bb
# rhel08:       52:54:00:43:26:d3
# rhel09:       52:54:00:7f:e1:4e
# upgraded08:   52:54:00:22:37:93
# upgraded09:   52:54:00:e6:14:ee

# Get the IP of the VM belonging to cento based on arp.
while ! [ $( arp -an | grep 52:54:00:d6:0c:72| awk '{print $2}' | tr -d '()' )  ]; do echo "Waiting for arp to return vm1 MAC address."; sleep 10; done;
echo "$( arp -an | grep 52:54:00:d6:0c:72| awk '{print $2}' | tr -d '()' ) vm1" >> /etc/hosts

#while ! ping -c 1 -W 1 vm1; do echo "Waiting for vm1 - network interface might be down."; sleep 10; done;

virsh attach-interface --domain vm1 --type network --source default --model virtio