#!/bin/bash
set -euxo pipefail

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

echo "Setup script for satellite"

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

echo "Adding wheel" > /root/post-run.log
useradd rhel
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "DONE" >> /root/post-run.log

echo "export LANG=en_US.UTF-8" >> /root/.bashrc

#hammer -u admin -p bc31c9a6-9ff0-11ec-9587-00155d1b0702 subscription upload --file /home/myee/manifest_satellite-6.10-instruqt_20230425T175412Z.zip --organization "Acme Org"
hammer -u admin -p bc31c9a6-9ff0-11ec-9587-00155d1b0702 subscription upload --file /home/myee/manifest_satellite-6.14-instruqt_20240209T173754Z.zip --organization "Acme Org"
rm -rf /home/myee/manifest_satellite-*

hammer subscription refresh-manifest --organization "Acme Org"

# Edit the wireguard if wg0 to include the following config.

cat << EOL > /etc/wireguard/wg0.conf
# satellite
[Interface]
Address = 192.0.2.1
ListenPort = 51820
PrivateKey = 6LXqhMZXv1vrZolWq2GpU5fCmDnFZgkBm6kkoCfIW3M=

# rhel1
[Peer]
PublicKey = tDS5lI+Dbf0I+p49bCjKJ+Q7QIrzwh3B1Zx3gxWXzFM=
AllowedIPs = 192.0.2.2/32

# rhel2
[Peer]
PublicKey = vZzGfBInJWpI7U1KwjNLdNn0z/rjVAeHJjJX093Dxys=
AllowedIPs = 192.0.2.3/32

# satellite-2
[Peer]
PublicKey = r4AnEsHQaftmMX27FRib6CK0NoMyjgUnxS6Pdbf5ZxQ=
AllowedIPs = 192.0.2.4/32

# capsule
[Peer]
PublicKey = uTwxPNMJEn0ArFXxZN8VhZIqo1xKc/mLJtkj86oJMWQ=
AllowedIPs = 192.0.2.5/32
EOL

nmcli con del wg0
nmcli connection import type wireguard file /etc/wireguard/wg0.conf
nmcli con mod wg0 ipv4.dns 192.0.2.1

hammer repository-set enable --organization-id 1 --id 7441 --releasever 8
hammer repository-set enable --organization-id 1 --id 7416 --releasever 8
hammer repository synchronize --organization-id 1 --async --name "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8" --product "Red Hat Enterprise Linux for x86_64"
hammer repository synchronize --organization-id 1 --async --name "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8" --product "Red Hat Enterprise Linux for x86_64"